"""Add language to posts

Revision ID: 94de0e014334
Revises: 67bfdd279da9
Create Date: 2021-02-11 02:10:39.847789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94de0e014334'
down_revision = '67bfdd279da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'language')
    # ### end Alembic commands ###
